# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v6.1.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod:
  hosts:www.habahaba.store: null
domains_test:
  hosts:property.habahaba.store: null
gitlab_url: https://gitlab.com/gechcode-odoo/property
odoo_dbfilter: ^prod
odoo_initial_lang: en_US
odoo_listdb: true
odoo_oci_image: docker.io/gechcode/property
odoo_proxy: traefik
odoo_version: 16.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_cidr_whitelist: null
postgres_dbname: prod
postgres_exposed: true
postgres_exposed_port: 5432
postgres_username: odoo
postgres_version: "15"
project_author: gechcode
project_license: BSL-1.0
project_name: property
smtp_canonical_default: habahaba.store
smtp_canonical_domains: []
smtp_default_from: odoo@habahaba.store
smtp_relay_host: pixel.mxrouting.net
smtp_relay_port: 587
smtp_relay_user: odoo@habahaba.store
smtp_relay_version: "13"
