name: ci

on:
  pull_request:
  push:
    branches:
      - devel
  schedule:
    # See https://crontab.guru/weekly
    - cron: 0 0 * * 0

jobs:
  build-push:
    runs-on: ubuntu-22.04
    needs: test
    strategy:
      fail-fast: false
      matrix:
        odoo_version: ["16.0"]
        platforms: ["linux/amd64", "linux/arm64"]
    env:
      LATEST_RELEASE: "16.0"
      DOCKER_REPO: gechcode/property
      GHCR_HOST: ghcr.io
    steps:
      - name: Set build date
        run: echo "BUILD_DATE=$(date '+%Y-%m-%dT%H:%M:%S.%N%:z')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.BOT_LOGIN }}
          password: ${{ secrets.BOT_TOKEN }}
      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.odoo_version }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_REPO }}:${{ matrix.odoo_version }}
            ${{ env.GHCR_HOST }}/${{ env.DOCKER_REPO }}:${{ matrix.odoo_version }}
            ${{ matrix.odoo_version == env.LATEST_RELEASE && format('{0}:latest', env.DOCKER_REPO) || '' }}
            ${{ matrix.odoo_version == env.LATEST_RELEASE && format('{0}/{1}:latest', env.GHCR_HOST, env.DOCKER_REPO) || '' }}
          target: base
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            ODOO_VERSION=${{ matrix.odoo_version }}
      - name: Build onbuild image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.odoo_version }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_REPO }}:${{ matrix.odoo_version }}-onbuild
            ${{ env.GHCR_HOST }}/${{ env.DOCKER_REPO }}:${{ matrix.odoo_version }}-onbuild
            ${{ matrix.odoo_version == env.LATEST_RELEASE && format('{0}:latest-onbuild', env.DOCKER_REPO) || '' }}
            ${{ matrix.odoo_version == env.LATEST_RELEASE && format('{0}/{1}:latest-onbuild', env.GHCR_HOST, env.DOCKER_REPO) || '' }}
          target: onbuild
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            ODOO_VERSION=${{ matrix.odoo_version }}
            - name: Deploy App to Caprover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
